<!DOCTYPEhtml>
<html>
<head>
<title>TeacherDetails</title>
<scriptsrc=https://code.jquery.com/jquery-3.6.0.min.js></script>
</head>
<body>
<selectid=”teacher-list”>
<optionvalue=””>--SelectTeacher--</option>
<optionvalue=”1”>JohnDoe</option>
<optionvalue=”2”>JaneSmith</option>
<optionvalue=”3”>BobJohnson</option>
</select>
<buttonid=”submit-btn”>GetDetails</button>
<divid=”details”></div>
<script>
$(document).ready(function(){
$(‘#submit-btn’).click(function(){
Vartno=$(‘#teacher-list’).val();
If(tno==‘’){
Alert(‘Pleaseselectateacher.’);
Return;
}
$.ajax({
url:‘teacherdetails.php’,
method:‘POST’,
data:{tno:tno},
success:function(response){
$(‘#details’).html(response);
},
Error:function(xhr,status,error){
Console.log(xhr.responseText);
}
});
});
});
</script>
</body>
</html>